tags:
  - Tasks
summary: Get user tasks
description: Get all tasks of the authenticated user
security:
  - bearerAuth: []
responses:
  '200':
    description: List of tasks
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            data:
              type: array
              items:
                $ref: '../../components/schemas/tasks.yaml'
