tags:
  - Tasks
summary: Get user tasks
operationId: getTasks
description: Get all tasks of the authenticated user
security:
  - bearerAuth: []
parameters:
  - in: query
    name: isDone
    schema:
      type: boolean
      enum: [true, false]
    required: false
    description: Filter tasks by completion status
responses:
  '200':
    description: List of tasks
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            data:
              type: array
              items:
                $ref: '../../components/schemas/tasks.yaml'
  '401':
    description: Unauthorized
    content:
      application/json:
        schema:
          $ref: '../../components/responses/401.yaml'
