tags:
  - Tasks
summary: Toggle task status
operationId: updateUser
description: Change task status (done / not done)
security:
  - bearerAuth: []
parameters:
  - in: path
    name: id
    required: true
    schema:
      type: string
    description: Task ID
responses:
  '200':
    description: Status updated
    content:
      application/json:
        schema:
          type: object
          properties:
            status:
              type: integer
              example: 200
            message:
              type: string
              example: Status updated
            data:
              $ref: '../../components/schemas/tasks.yaml'
  '404':
    description: Task not fou
